### ISSUE TITLE
parse MLME contents

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/dissectors#1]

**Comment by twatteyne** [comment]
Although the comment of 6a7470e559bdc222eadaef286e0cfcaf446f3e9f seems to indicate that MLME are now parsed, I still get 28 bytes of unparsed data in an EB,

**Comment by jmmunoz86** [comment]
At the moment, all the nested IEs within the MLME IE are classified.

**Comment by twatteyne** [comment]
Absolutely, I rebuilt everything yesterday, works fine!
