### ISSUE TITLE
Information Elements: Unknown (0x2198)

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/dissectors#2]
Testing with 6a7470e559bdc222eadaef286e0cfcaf446f3e9f, "Information Elements: Unknown (0x2198)" appear, for example in the ACK packets. It looks like the dissector is trying to parsing the CRC field.

**Comment by twatteyne** [comment]
@jmmunoz86  test

**Comment by jmmunoz86** [comment]
This issue was due to the impossibility of recognizing the FCS field when dissecting the Header IE list. It is now solved.

**Comment by twatteyne** [comment]
That's fantastic! To show which commit fixed the issue, you can write, in your commit message, something lik "Fixes #2". GitHub will then automatically put hyperlinks between the commit message (https://github.com/openwsn-berkeley/dissectors/commits/master) and the issue.
