### ISSUE TITLE
put raw payload of IEs after header

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/dissectors#5]
Some IEs aren't completely parsed by the dissector. I understand this is a bit of work and needs some time to be done, no problem. In the meantime, however, would it be possible to display the payload of those IEs after the IE header in the parsed output?

**Comment by jmmunoz86** [comment]
I am about to start with that, the nested IEs. However, as is now, are all the IE classified (Header, Payload IEs)?

**Comment by twatteyne** [comment]
AFAICT, yes (at least the ones used in draft-minimal). One thing is that the "TSCH timeslot IE", etc appears at the same level as the MLME IE, but should be nested within that, no?

**Comment by jmmunoz86** [comment]
yes, you're right. I will check it out to see how I can get it done.

2015-07-02 9:16 GMT+02:00 Thomas Watteyne notifications@github.com:

> AFAICT, yes (at least the ones used in draft-minimal). One thing is that
> the "TSCH timeslot IE", etc appears at the same level as the MLME IE, but
> should be nested within that, no?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openwsn-berkeley/dissectors/issues/5#issuecomment-117938844
> .

## 

Jonathan Muñoz

**Comment by jmmunoz86** [comment]
please check the latest commit.

**Comment by twatteyne** [comment]
will do, thanks.

**Comment by Guillaumegaillard** [comment]
In the current version, the payload appears after each IE, Jonathan is
working to make it appear inside each IE. This should be updated soon :)

Guillaume

2015-07-05 19:53 GMT+02:00 Thomas Watteyne notifications@github.com:

**Comment by twatteyne** [comment]
OK, thanks. To publish the draft with the results, I will have to freeze the implementation tonight and dot the capturing. Please stop me if you plan on fixing this still tonight.

**Comment by Guillaumegaillard** [comment]
Thomas,
We plan to fix it tomorrow. So if you feel  the latest commit is not
suitable, please use the previous one (7c4db7f
https://github.com/openwsn-berkeley/dissectors/commit/7c4db7fc7d81a931b1700e5141c1f215976cc248).
I think both are valid but not completely satisfactory.

Guillaume

2015-07-05 20:27 GMT+02:00 Thomas Watteyne notifications@github.com:

**Comment by twatteyne** [comment]
OK, thanks
