### ISSUE TITLE
PAN ID compression combination from Table 2a

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/dissectors#6]
@jmmunoz86, @mstaflex
OK, change of plans. We need the following combination to be parsed correctly (please unicast me for details): Table 2a, row 12:
- Source address: present
- Destination address: present
- Frame version: b10
- Frame types: Beacon, Data, Acknowledgment, MAC, Multipurpose
- Source PAN ID: Not Present
- Destination PAN ID: Present
- PAN ID compression: 0

**Comment by twatteyne** [comment]
@changtengfei fixed https://openwsn.atlassian.net/browse/FW-422, but now the dissector parses things wrong. I have uploaded the corresponding pcap at https://openwsn.atlassian.net/browse/FW-422, which you can use to fix this issue.

**Comment by twatteyne** [comment]
yaay, works like a charm, thanks!

**Comment by mstaflex** [comment]
:+1:
